name: continuous Integration Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.12'

    - name: All dependencies Install
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
        
    - name: Test and Run
      run: |
        chmod +x project/tests.sh
        project/tests.sh